"""Medical summary PDF generation service for MotherCare AI.

Security requirements:
- No internal doctor notes visible to patients.
- No audit logs, passwords, tokens, or hidden instructions in PDF.
- Temporary file is deleted after streaming.
- Path traversal prevention: only temp files created via tempfile module.
- Clearly labelled: deterministic screening, ML estimates, clinician decisions.
- AI outputs labelled as decision support, NOT diagnosis.
- Tamil Unicode supported where ReportLab allows.
"""
import os
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Optional

from sqlalchemy.orm import Session

from app.db import models
from app.utils.logger import logger

DISCLAIMER = (
    "IMPORTANT DISCLAIMER: This document is a decision-support summary generated by MotherCare AI. "
    "It is NOT a medical diagnosis. AI-generated outputs are for decision support only and must be "
    "reviewed by a qualified healthcare professional. Do not rely on this document for clinical decisions."
)


def _try_import_reportlab():
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.platypus import PageBreak
        return True
    except ImportError:
        return False


def _make_page_callback():
    """Return a page callback that draws page numbers. Imports are self-contained."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm

    def on_page(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        page_num = canvas.getPageNumber()
        canvas.drawRightString(A4[0] - 1.5 * cm, 1 * cm, f"Page {page_num}")
        canvas.drawString(1.5 * cm, 1 * cm, "MotherCare AI — Decision Support Only, Not a Diagnosis")
        canvas.restoreState()

    return on_page


def generate_medical_summary_pdf(
    db: Session,
    patient: models.User,
    requesting_user: models.User,
) -> Optional[Path]:
    """
    Generate and return path to a temporary PDF file.
    Caller MUST delete the file after streaming it to the client.

    Returns None if ReportLab is not available (fallback to plaintext).
    """
    if not _try_import_reportlab():
        logger.warning("ReportLab not installed. Cannot generate PDF.")
        return None

    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    from reportlab.platypus import PageBreak

    # ── Create secure temp file ────────────────────────────────────────────────
    tmp = tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".pdf",
        prefix="mc_summary_",
        dir=tempfile.gettempdir(),
    )
    tmp_path = Path(tmp.name)
    tmp.close()

    # ── Build document ─────────────────────────────────────────────────────────
    doc = SimpleDocTemplate(
        str(tmp_path),
        pagesize=A4,
        rightMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title="MotherCare AI Medical Summary",
        author="MotherCare AI",
    )

    styles = getSampleStyleSheet()
    title_style  = ParagraphStyle("title",  parent=styles["Title"],  fontSize=18, spaceAfter=12)
    h1_style     = ParagraphStyle("h1",     parent=styles["Heading1"], fontSize=14, spaceAfter=6)
    h2_style     = ParagraphStyle("h2",     parent=styles["Heading2"], fontSize=11, spaceAfter=4)
    body_style   = ParagraphStyle("body",   parent=styles["Normal"],  fontSize=9,  spaceAfter=3)
    warn_style   = ParagraphStyle("warn",   parent=styles["Normal"],  fontSize=9,  spaceAfter=3,
                                  textColor=colors.darkred)
    label_style  = ParagraphStyle("label",  parent=styles["Normal"],  fontSize=8,  textColor=colors.grey)
    ai_style     = ParagraphStyle("ai",     parent=styles["Normal"],  fontSize=9,  spaceAfter=3,
                                  textColor=colors.navy)

    story = []
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # ── Title block ────────────────────────────────────────────────────────────
    story.append(Paragraph("MotherCare AI — Patient Medical Summary", title_style))
    story.append(Paragraph(f"Generated: {generated_at}", label_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.teal))
    story.append(Spacer(1, 0.3 * cm))

    # ── Disclaimer ─────────────────────────────────────────────────────────────
    story.append(Paragraph("⚠ DISCLAIMER", h2_style))
    story.append(Paragraph(DISCLAIMER, warn_style))
    story.append(Spacer(1, 0.4 * cm))

    # ── Section 1: Patient Profile ─────────────────────────────────────────────
    story.append(Paragraph("1. Patient Profile", h1_style))
    story.append(Paragraph(f"Username: {patient.username}", body_style))
    story.append(Paragraph(f"Language preference: {patient.language}", body_style))
    story.append(Paragraph(f"Account created: {patient.created_at.strftime('%Y-%m-%d') if patient.created_at else 'N/A'}", body_style))
    story.append(Spacer(1, 0.3 * cm))

    # ── Section 2: Pregnancy / Digital Twin ────────────────────────────────────
    story.append(Paragraph("2. Pregnancy & Vital Information", h1_style))
    twin = db.query(models.DigitalTwin).filter_by(user_id=patient.id).first()
    if twin:
        vitals = [
            ["Parameter", "Value"],
            ["Gestational Week", f"{twin.current_week:.1f}"],
            ["Due Date", twin.due_date or "Not set"],
            ["Systolic BP (mmHg)", f"{twin.systolic_bp:.0f}"],
            ["Diastolic BP (mmHg)", f"{twin.diastolic_bp:.0f}"],
            ["Heart Rate (bpm)", f"{twin.heart_rate:.0f}"],
            ["Body Temperature (°F)", f"{twin.body_temp:.1f}"],
            ["Glucose (mg/dL)", f"{twin.glucose_level:.0f}"],
            ["Hemoglobin (g/dL)", f"{twin.hemoglobin:.1f}"],
            ["BMI", f"{twin.bmi:.1f}"],
        ]
        tbl = Table(vitals, colWidths=[8 * cm, 6 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.teal),
            ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
            ("FONTSIZE",   (0, 0), (-1, -1), 9),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.lightyellow]),
        ]))
        story.append(tbl)
        story.append(Paragraph("[Source: Digital Twin biomarker record — last updated automatically from patient inputs]", label_style))
    else:
        story.append(Paragraph("No digital twin data available.", body_style))
    story.append(Spacer(1, 0.3 * cm))

    # ── Section 3: Red-Flag History (deterministic) ────────────────────────────
    story.append(Paragraph("3. Red-Flag Screening History (Deterministic Rules)", h1_style))
    story.append(Paragraph("[Source: Deterministic rule-based emergency screening — not AI]", label_style))

    alerts = (
        db.query(models.MaternalRiskAlert)
        .filter_by(patient_id=patient.id, alert_source="deterministic")
        .order_by(models.MaternalRiskAlert.created_at.desc())
        .limit(20)
        .all()
    )
    if alerts:
        rows = [["Date", "Risk Level", "Warning Signs", "Status"]]
        for a in alerts:
            rows.append([
                a.created_at.strftime("%Y-%m-%d") if a.created_at else "",
                a.risk_level,
                (a.warning_signs or "")[:80] + ("..." if a.warning_signs and len(a.warning_signs) > 80 else ""),
                a.status,
            ])
        tbl = Table(rows, colWidths=[3 * cm, 3 * cm, 9 * cm, 3 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.teal),
            ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
            ("FONTSIZE",   (0, 0), (-1, -1), 8),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ]))
        story.append(tbl)
    else:
        story.append(Paragraph("No deterministic red-flag alerts recorded.", body_style))
    story.append(Spacer(1, 0.3 * cm))

    # ── Section 4: ML Risk History ─────────────────────────────────────────────
    story.append(Paragraph("4. ML-Based Risk Estimates [AI Decision Support — Not Diagnosis]", h1_style))
    story.append(Paragraph("[Source: Machine-learning model — estimates only, reviewed by clinicians]", label_style))

    ml_alerts = (
        db.query(models.MaternalRiskAlert)
        .filter_by(patient_id=patient.id, alert_source="ml")
        .order_by(models.MaternalRiskAlert.created_at.desc())
        .limit(20)
        .all()
    )
    if ml_alerts:
        rows = [["Date", "Risk Level", "Confidence", "Model Ver.", "Clinician Status"]]
        for a in ml_alerts:
            conf = f"{a.confidence:.0%}" if a.confidence is not None else "N/A"
            rows.append([
                a.created_at.strftime("%Y-%m-%d") if a.created_at else "",
                a.risk_level,
                conf,
                a.model_version or "N/A",
                a.status,
            ])
        tbl = Table(rows, colWidths=[3 * cm, 3 * cm, 3 * cm, 3 * cm, 6 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.navy),
            ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
            ("FONTSIZE",   (0, 0), (-1, -1), 8),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ]))
        story.append(tbl)
        story.append(Paragraph("⚠ ML estimates are NOT diagnoses. They require clinician review.", ai_style))
    else:
        story.append(Paragraph("No ML risk alerts recorded.", body_style))
    story.append(Spacer(1, 0.3 * cm))

    # ── Section 5: Doctor-Reviewed Alerts ─────────────────────────────────────
    story.append(Paragraph("5. Clinician-Reviewed Alerts", h1_style))
    reviewed = (
        db.query(models.MaternalRiskAlert)
        .filter(
            models.MaternalRiskAlert.patient_id == patient.id,
            models.MaternalRiskAlert.status.in_(["resolved", "dismissed_as_false_positive", "escalated"]),
        )
        .order_by(models.MaternalRiskAlert.review_timestamp.desc())
        .limit(20)
        .all()
    )
    if reviewed:
        for a in reviewed:
            ts = a.review_timestamp.strftime("%Y-%m-%d") if a.review_timestamp else "N/A"
            story.append(Paragraph(
                f"• [{ts}] {a.risk_level} — {a.status} — {(a.resolution_reason or 'No reason recorded')[:100]}",
                body_style,
            ))
    else:
        story.append(Paragraph("No clinician-reviewed alerts recorded.", body_style))
    story.append(Spacer(1, 0.3 * cm))

    # ── Section 6: Appointments ────────────────────────────────────────────────
    story.append(Paragraph("6. Appointments", h1_style))
    appts = (
        db.query(models.Appointment)
        .filter_by(patient_id=patient.id)
        .order_by(models.Appointment.appointment_datetime.desc())
        .limit(20)
        .all()
    )
    if appts:
        rows = [["Date/Time", "Type", "Status", "Patient Instructions"]]
        for ap in appts:
            rows.append([
                ap.appointment_datetime.strftime("%Y-%m-%d %H:%M") if ap.appointment_datetime else "",
                ap.appointment_type,
                ap.status,
                (ap.patient_instructions or "")[:60],
            ])
        tbl = Table(rows, colWidths=[4 * cm, 3 * cm, 3 * cm, 8 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.teal),
            ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
            ("FONTSIZE",   (0, 0), (-1, -1), 8),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ]))
        story.append(tbl)
        story.append(Paragraph("Note: Internal doctor notes are not included in this summary.", label_style))
    else:
        story.append(Paragraph("No appointments recorded.", body_style))
    story.append(Spacer(1, 0.3 * cm))

    # ── Section 7: Doctor-Published Instructions ───────────────────────────────
    story.append(Paragraph("7. Active Clinical Care Instructions (Doctor-Published)", h1_style))
    now = datetime.utcnow()
    instrs = (
        db.query(models.PatientInstruction)
        .filter(
            models.PatientInstruction.patient_id == patient.id,
            models.PatientInstruction.status == "active",
            (models.PatientInstruction.expiry_date == None)
            | (models.PatientInstruction.expiry_date > now),
        )
        .all()
    )
    # Filter patient-visible only
    visible = []
    for i in instrs:
        vis = i.patient_visible
        if isinstance(vis, str):
            if vis.lower() in ("true", "1"):
                visible.append(i)
        elif vis:
            visible.append(i)

    if visible:
        for i in visible:
            story.append(Paragraph(
                f"• [{i.priority}] {i.message[:200]}",
                body_style,
            ))
    else:
        story.append(Paragraph("No active clinical instructions.", body_style))
    story.append(Spacer(1, 0.3 * cm))

    # ── Section 8: Medicine Reminders ─────────────────────────────────────────
    story.append(Paragraph("8. Medicine Reminders", h1_style))
    reminders = (
        db.query(models.MedicineReminder)
        .filter_by(patient_id=patient.id)
        .all()
    )
    active_reminders = [r for r in reminders if _bool_val_pdf(r.is_active)]

    if active_reminders:
        rows = [["Medicine", "Dosage", "Frequency", "Source", "Start Date"]]
        for r in active_reminders:
            rows.append([
                r.medicine_name,
                r.dosage,
                r.frequency,
                r.source,
                r.start_date.strftime("%Y-%m-%d") if r.start_date else "N/A",
            ])
        tbl = Table(rows, colWidths=[4 * cm, 3 * cm, 4 * cm, 3 * cm, 4 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.teal),
            ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
            ("FONTSIZE",   (0, 0), (-1, -1), 8),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ]))
        story.append(tbl)
        story.append(Paragraph(
            "⚠ Medicine reminders are not prescriptions. Confirm all medications with your doctor.",
            ai_style,
        ))
    else:
        story.append(Paragraph("No active medicine reminders.", body_style))
    story.append(Spacer(1, 0.3 * cm))

    # ── Section 9: Final disclaimer ────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=1, color=colors.teal))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph("Evidence-Source References", h2_style))
    story.append(Paragraph(
        "All deterministic rules are based on validated WHO maternal health guidelines. "
        "ML risk estimates are derived from a trained classification model (version recorded per alert). "
        "RAG citations are referenced from approved institutional guidelines uploaded by administrators.",
        body_style,
    ))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(DISCLAIMER, warn_style))

    # ── Build PDF ──────────────────────────────────────────────────────────────
    on_page = _make_page_callback()
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    logger.info("PDF generated: %s for patient=%s", tmp_path.name, patient.id)
    return tmp_path


def _bool_val_pdf(v) -> bool:
    if isinstance(v, str):
        return v.lower() in ("true", "1")
    return bool(v)
